= Išvados


Rekurentinės diagramos yra naudingas įrankis analizuojant signalus. Šios diagramos gali atskleisti signalų savybes, kurios nėra akivaizdžios iš pačio signalo. Vienas iš pavyzdžių galėtų būti @logistic, kuriame pavaizduotos logistinio atvaizdžio rekurentinės diagramos. Jos rodo trumpus kvazi-periodus, nors pats signalas iš pirmo žvilgsnio nieko nesiskiria nuo atsitiktinio signalo. Norint, kad ši technika būtų naudinga, reikia gebėti atlikti nepaprastą uždavinį -- pasirinkti algoritmo parametrus taip, kad diagramoje būtų atskleistos visos detalės. Šių parametrų yra keletas, o kiekvienas iš jų turi savo unikalų poveikį:

- $r$ parametras nustato slenkstinę reikšmę dvieju signalo atkarpų lyginimui ir nustato ar taškas turėtų būti spalvinamas juodai arba baltai. Tinkamai pasirinkti šio signalo reikšmę yra labai svarbu, nes tai gali turėti didelį poveikį diagramos išvaizdai, pavyzdžiu galėtume laikyti logistinio atvaizdžio diagramą @logistic, kur maža $r$ reikšmė atskleidžia homogenišką ir netvarkingą taškų pasiskirstymą, kuris nėra toks akivaizdus pažvelgus į diagramą su didesne $r$ parametro reikšme.
- $D$ parametras nustato kiek signalo taškų lyginsime spręsdami vieno taško spalvą. Šio parametro didinimas turi glotninantį efektą panašų į Gauso suliejimą. Tai akivaizdžiai matome diagramoje gautoje iš įmonės "Apple Inc." akcijų svyravymo @finance.
- $d$ parametras reguliuoja atstumą tarp signalo taškų, kuriuos renkamės lyginimui, kai $d=1$ imsime taškus, kurie yra šalia vienas kito, kai $d=2$ imsime kas antrą tašką ir t. t. Šio parametro didinimas turi dvejinantį efektą dėl kurio gali pranykti diagramos struktūra. To pavyzdys galėtų būti, kuriame matome, kad diagrama gauta naudojant $d=2$ turi vos matomų vertikalių ir horizontalių baltų linijų, tačiau padidinus $d$ iki 5, vaizdas tampa mažiau aiškus.
- $p$ parametras nėra apibrėžtas klasikiniame rekurentinių diagramų algoritme, o yra tik šios uždouties dalis. Jis kontroliuoja procentą juodų taškų skaičiaus diagramoje. Algoritmo įgyvendinime parametras $p$ yra naudojamas tik parametro $r$ apskaičiavimui, todėl kokybinis šio parametro didinimo efektas yra toks pat kaip parametro $r$. Tai gana aiškiai matosi iliustracijose @logistic ir @air_quality_rd. Iš praktinės pusės, šį parametrą naudoti yra patogiau nei parametrą $r$, todėl, kad ne visada galime lengvai žinoti kokia slenkstinė reikšmė bus tinkama. Taip pat todėl, kad naudojant parametrą $p$ yra lengviau numatyti algoritmo rezultatą.
- Norma taip yra vienas iš algoritmo parametrų, kurį galime pasirinkti. Praktinis efektas diagramoms yra skirtingas juodų taškų skaičius. Kai naudojama Manheteno norma, juodų taškų bus šiek tiek mažiau nei tuomet, jei būtų naudojama Euklidinė norma, o daugiausiai juodų taškų atsiranda tada, kai naudojama maksimumo norma. Tai galima matyti iliustracijoje @lung_sound_rd.

